### ISSUE TITLE
Launcher hangs upon start

### ISSUE THREAD

**Issue by goooroooX** [loueradun/GamestreamLauncher#5]
Hi,

During tool starting it just hangs after either manual start or start via GameStream. It says "Enable munti-controller mode" and never go further, even after enabling this mode. API call to Awesome Miner is OK - miner gets stopped.

![GameStream Launcher 1](https://user-images.githubusercontent.com/27283908/121866902-0effa700-cd08-11eb-9517-7535aa3270cb.jpg)

![GameStream Launcher 2](https://user-images.githubusercontent.com/27283908/121866951-1e7ef000-cd08-11eb-9398-35a5669d7da8.jpg)

**Comment by goooroooX** [comment]
Windows 10 Professional, version: 20H2 (build 19042.1052).

**Comment by loueradun** [comment]
Try it without setting the custom resolution.  There may be a bug with that
setting when there is only 1 monitor connected, but I need to investigate.

It has been a few days since I have worked on the project, but the code to
save/load monitor settings was originally intended to be used for
enabling/disabling multiple monitors, and I had later added the support to
set the resolution on your main.  I may have overlooked the condition of
this being used as a single display as this is not my daily use case.

**Comment by goooroooX** [comment]
Have tried it from the beginning - launcher does not allow to have empty resolution field.

![2021-06-14_164059](https://user-images.githubusercontent.com/27283908/121901880-79780d80-cd2f-11eb-962f-81be0073cc40.jpg)

**Comment by loueradun** [comment]
I just pushed a new release that better handles the parsing of the output from the monitor info derived from the MultiMonitorTool that is used to obtain/modify monitor settings.

I believe this should resolve your issue.
https://github.com/loueradun/GamestreamLauncher/releases/tag/1.3.1

**Comment by goooroooX** [comment]
Works fine now. 
Custom resolution still can't be set to empty value, and I believe that can be the reason for desktop to switch resolutions when executing/ending launcher, which lead to all opened windows change their sizes. 
Not critical, but annoying.

**Comment by goooroooX** [comment]
One feature request, when possible... When the game/app was added manually to GameStream and exit after the session, the streaming of desktop is still running (you need to exit manually). Is it possible to end streaming gracefully (I believe I can just kill nvstreamer.exe with custom script, but this will cause a connection lost message)?

**Comment by loueradun** [comment]
Regarding the custom resolution setting;  If I find some time, I will look
into making it optional and disabling the monitor adjustment settings
completely when set this way.  You could go back a revision or two before I
implemented it, as it was added by request for another user.

As to exiting Gamestream gracefully, with the service installed by the
GamestreamLauncher, it should properly monitor the exe that you launched
and stop and start the nvcontainer service when that exe stops running.
That does produce a "connection lost" message.  I have not found any way to
request the service to end the session in a clean way unfortunately.

That said, I don't think there should be a case where the stream continues
after launched exe has exited.  Is the launcher continuing to run while you
are using the application, and then when you exit the application, properly
re-enabling the miner but not closing the streaming session?  Or are you
ending the streaming session through some other method like using the quit
button from the shield device (this should trigger a force close of
the Launcher and all executables spawned in its chain like any other
game/application)?

**Comment by goooroooX** [comment]
nvstreamer.exe is not a service. When terminated, NVidia Games on Shield TV gives you an error message and hanged image (have to press OK to get rid of it). This problem with proper stream session closing is not just for this particular case with launcher. I can execute any available game, exit from it properly - and streaming will not end.

**Comment by loueradun** [comment]
I guess I am still not understanding.  Could you provide some additional info about how you are quitting the stream?

The Launcher works by installing it's own service named NvContainerRestart to monitor for active streams.  When it detects the launched exe has stopped, it stops nvcontainer.exe (which is a service named NvContainerLocalSystem).  A few seconds later it will re-enable the service, allowing you to stream again.

The only other way to "exit" the stream is through the interface on the remote device.  If you hit "Exit" from the menu on your Shield, it should close the launcher and all software opened by it.

Of course you could also exit the stream by pressing the home button (which would leave the stream still active in the background).

Are you having an issue with one of the methods for closing the stream above, or exiting the stream in some other manner?

**Comment by goooroooX** [comment]
Thank you for clarification. It seems NvContainerRestart service was never installed on my system. 

> Uninstalling assembly 'E:\GameStreamLauncher\Binaries\NvContainerRestart.exe'.
> Affected parameters are:
>    logtoconsole = 
>    assemblypath = E:\GameStreamLauncher\Binaries\NvContainerRestart.exe
>    logfile = E:\GameStreamLauncher\Binaries\NvContainerRestart.InstallLog
> Removing EventLog source NvContainerRestart.
> Warning: The source NvContainerRestart is not registered on the local machine.
> Service NvContainerRestart is being removed from the system...
> An exception occurred during the uninstallation of the System.ServiceProcess.ServiceInstaller installer.
> System.ComponentModel.Win32Exception: The specified service does not exist as an installed service
> An exception occurred while uninstalling. This exception will be ignored and the uninstall will continue. However, the application might not be fully uninstalled after the uninstall is complete.

![image](https://user-images.githubusercontent.com/27283908/123002872-16cfe300-d3bb-11eb-9dcc-b83053ae6f55.png)

Can you suggest how to install it?

**Comment by goooroooX** [comment]
I have managed to make it work. Below are troubleshooting steps.

1. Install NvContainerRestart.exe with InstallUtil.exe - OK
2. Run GameStream session - OK, but failed to close stream at the end
3. Re-configure with GamestreamLauncherConfig.bat - OK, this time service was properly uninstalled and then installed again
4. Run GameStream session - OK, session ended (with "connection terminated" warning on Shield side)

So, I think the problem with service installation routine: when the service is not installed initially, Launcher configuration procedure will fail to uninstall service, and terminates whole sequence.
